# Generated by Django 5.0.6 on 2024-06-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='formato',
            field=models.CharField(max_length=20),
        ),
    ]
